update from angular 1x to angular 2x convention
stevemao/conventional-changelog-angular pull request #17
Opened 2016-11-02 18:50 UTC by ellerbrock

### Update Information:

Update commit convention from [Angular 1x](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#type) to [Angular 2x](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type).

to be compatible with: [Commitizen conventional-commit-types](https://github.com/commitizen/conventional-commit-types/blob/master/index.json) - added build + ci

i also made a pull request yesterday which got through to [conventional-changelog-lint-config-angular](https://github.com/marionebl/conventional-changelog-lint-config-angular/pull/3) to fix lint errors with [[conventional-changelog-lint](https://github.com/marionebl/conventional-changelog-lint).

example usage and boilerplate for beginners could be found here: [node-developer-boilerplate](https://github.com/ellerbrock/node-developer-boilerplate).

and thanks for your work. i forked your repo and added emoji support here: [conventional-changelog-angular-emoji](https://github.com/ellerbrock/conventional-changelog-angular-emoji)

have fun and happy hacking!

![woop woop](http://i.giphy.com/18pjPEqqIt2k8.gif)

2016-11-02 21:53 UTC, stevemao commented
Thanks for your PR 😄

2016-11-02 21:55 UTC, stevemao requested changes
Thanks for the hard work 😃

2016-11-02 21:55 UTC, stevemao commented on index.js
> +    // added: build, ci
I don't think the comments here is needed

2016-11-02 21:55 UTC, stevemao commented on index.js
> -    } else if (commit.type === 'perf') {
Why do you move these down?

2016-11-02 21:55 UTC, stevemao commented on package.json
> +  "version": "1.4.0",
None of the bumps here is necessary :)

2016-11-02 21:56 UTC, ellerbrock commented
no worries!

![commitizen emoji](https://github.frapsoft.com/top/commitizen-emoji.jpg?v=101)

by the way you can run now commitzen via emojis in the shell :)

[cz-conventional-changelog-emoji](https://github.com/ellerbrock/cz-conventional-changelog-emoji)

2016-11-02 23:41 UTC, stevemao requested changes

2016-11-02 23:41 UTC, stevemao commented on index.js
> -    } else if (commit.type === 'perf') {
Sorry, Is there any reason to move this block down?

2016-11-02 23:41 UTC, stevemao commented on package.json
> -    "chai": "^3.4.1",
These bumps are not necessary. I'm using `^` here so it will get the latest changes (plus they are just devDeps).

2016-11-02 23:41 UTC, stevemao commented on test/test.js
> -        expect(chunk).to.not.include('first commit');
Not sure why this change?

2017-01-27 15:45 UTC, ihodev commented
@ellerbrock Please add requested changes :pray: Really appreciate your work and want to use Angular 2x commit convention :wink:

2018-02-05 14:26 UTC, hbetts commented
We're closing this pull request out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the pull request against the `conventional-changelog` mono-repository.

2018-02-05 14:26 UTC, closed without merging